// Generated by CoffeeScript 1.7.1
var fibrous,
  __slice = [].slice;

fibrous = require('fibrous');

['it', 'before', 'beforeEach', 'after', 'afterEach'].forEach(function(mochaFn) {
  var fnWithoutFibrous;
  fnWithoutFibrous = global[mochaFn];
  return global[mochaFn] = function() {
    var args, fn, _i;
    args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), fn = arguments[_i++];
    if (!(fn != null ? fn.length : void 0)) {
      fn = fibrous(fn);
    }
    return fnWithoutFibrous.apply(null, __slice.call(args).concat([fn]));
  };
});
